import allinone as aio

mh=aio.MinHeap(5)
mh.addNode(34)
mh.addNode(20)
mh.addNode(40)
mh.addNode(14)
mh.addNode(36)
mh.increaseHeap(5)
mh.addNode(2)
mh.addNode(90)
mh.addNode(75)
print(f"Extracted Min Element : {mh.extractMin()}")
mh.show()
print(f"Extracted Min Element : {mh.extractMin()}")
mh.show()